import { exportRunExcel } from '../src/lib/payrollExport.js'

const run = {
  cutoffStart: '2026-03-01',
  cutoffEnd: '2026-03-15',
  status: 'draft',
  totalGross: 45602.57,
  totalDeductions: 9423.88,
  totalNet: 36178.69,
  branchId: { name: 'All branches', code: 'ALL' },
  notes: 'Diagnostic run',
  payslipItems: [
    {
      employeeId: 'e1',
      employeeCode: '1234',
      employeeName: 'Jason Gorospe',
      basicPay: 38461.54,
      overtimePay: 641.03,
      holidayPay: 0,
      nightDiffPay: 0,
      allowances: 0,
      grossPay: 39102.57,
      lateDeduction: 184.29,
      undertimeDeduction: 0,
      sssContribution: 787.5,
      philHealthContribution: 1250,
      pagIbigContribution: 50,
      withholdingTax: 6465.9,
      otherDeductions: 0,
      totalDeductions: 8737.69,
      netPay: 30364.88,
      regularHours: 88.4,
      overtimeHours: 1.07,
      nightDiffHours: 0,
      lateMinutes: 23,
      undertimeMinutes: 0,
      absentDays: 0,
    },
    {
      employeeId: 'e2',
      employeeCode: '123',
      employeeName: 'Patrick Santos',
      basicPay: 6500,
      overtimePay: 0,
      holidayPay: 0,
      nightDiffPay: 0,
      allowances: 0,
      grossPay: 6500,
      lateDeduction: 44.69,
      undertimeDeduction: 0,
      sssContribution: 380.25,
      philHealthContribution: 211.25,
      pagIbigContribution: 50,
      withholdingTax: 0,
      otherDeductions: 0,
      totalDeductions: 686.19,
      netPay: 5813.81,
      regularHours: 86.75,
      overtimeHours: 0,
      nightDiffHours: 0,
      lateMinutes: 33,
      undertimeMinutes: 0,
      absentDays: 0,
    },
  ],
}

const tenant = {
  name: 'DE WEBNET Payroll',
  settings: {
    payslip: {
      companyDisplayName: 'DE WEBNET Payroll',
      headerSubtitle: 'Payroll Report',
      companyAddressLine: 'Sample Address',
      footerNote: 'Generated by system',
      signatories: {
        preparedByName: 'Payroll Officer',
        preparedByTitle: 'Prepared By',
        reviewedByName: 'HR Manager',
        reviewedByTitle: 'Reviewed By',
        approvedByName: 'Authorized Signatory',
        approvedByTitle: 'Approved By',
        receivedByLabel: 'Received By Employee',
      },
    },
  },
}

try {
  await exportRunExcel(run, tenant)
  console.log('styled-export-ok')
} catch (error) {
  console.error('styled-export-failed')
  console.error(error?.stack || error)
  process.exitCode = 1
}
