/**
 * WebSocket Configuration
 */

export const WS_CONFIG = {
  URL: import.meta.env.VITE_WS_URL || 'ws://localhost:8080',
  RECONNECT_INTERVAL: 5000,
  MAX_RECONNECT_DELAY: 30000,
  HEARTBEAT_INTERVAL: 30000
}

export const MESSAGE_TYPES = {
  // From Server
  ATTENDANCE_LOGGED: 'ATTENDANCE_LOGGED',
  SYNC_STATUS: 'SYNC_STATUS',
  EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',
  SYSTEM_STATUS: 'SYSTEM_STATUS',
  ERROR: 'ERROR',
  RESPONSE: 'RESPONSE',

  // To Server
  ADD_EMPLOYEE: 'ADD_EMPLOYEE',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  GET_EMPLOYEES: 'GET_EMPLOYEES',
  GET_ATTENDANCE_LOGS: 'GET_ATTENDANCE_LOGS',
  FORCE_SYNC: 'FORCE_SYNC',

  // WebSocket Protocol
  IDENTIFY: 'IDENTIFY',
  PING: 'PING',
  PONG: 'PONG'
}
